# use Ubuntu 14.04LTS trusty
sudo: required
dist: trusty
language: python
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y python3-pyqt5
  - export PYTHONCMD=/usr/bin/python3
  - curl --silent --show-error --retry 5 https://bootstrap.pypa.io/get-pip.py | sudo $PYTHONCMD
  - sudo $PYTHONCMD -m pip install --upgrade setuptools virtualenv
  - $PYTHONCMD -m virtualenv --system-site-packages .env
  - source .env/bin/activate
  - pip install flake8 pytest
  - pip install -r requirements.txt
install:
  - pip install -v .
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
# commands to run tests
script:
  - flake8 --config=setup.cfg Lib/trufont
  - py.test -v -r a tests/
